.PHONY: all

all: aws.tf
	terraform apply

aws.tf:
	@echo "******************************************************"
	@echo "Please consult the README: Building the infrastructure"
	@echo "******************************************************"
	exit 1
